/**
 * Shared-state rate limiter using Redis.
 *
 * CRITICAL: Must use Redis, NOT in-memory Maps. With multiple pod
 * replicas, in-memory Maps would give each replica its own counter,
 * effectively multiplying the limit by replica count.
 *
 * Algorithm: sliding window with Redis sorted sets, decided and spent in one
 * server-side script.
 *
 * ── Why one script rather than a read and then a write ──
 *
 * A limiter that reads the count, decides, and then writes has a moment between
 * the read and the write in which the count it decided on is no longer the
 * count. Every concurrent request for the same key can observe the same
 * under-limit count before any of them has spent it, and all of them pass: the
 * cap is exceeded by however many requests are in flight together, which is
 * precisely when a limiter is load-bearing.
 *
 * The property that fixes it is atomicity, not a smaller window. A retry, a
 * shorter timeout, a mutex around the pair, or reading again after writing all
 * make the interleaving less likely and leave it reachable — they are tuning
 * parameters on a defect, and each one has a concurrency at which it fails
 * again. Redis executes a script to completion before any other command from
 * any other client, so there is no instant at which the count has been read and
 * not yet spent. There is nothing left to tune because there is no window.
 *
 * The script decides both keys together for the same reason. Two scripts, one
 * per key, would each be atomic and the pair would not: a request could spend a
 * user slot and then be refused by the workspace limit, charging a user for a
 * request that never ran.
 *
 * `member` is generated by the caller and passed in, never generated in Lua.
 * A script that invents its own values is not a function of its inputs, and two
 * replicas of the same script would disagree.
 *
 * Port-injected so tests can pass a fake Redis implementing only the methods the
 * limiter actually uses — no vi.mock("ioredis").
 */
import { logger } from "../logger.js";

export interface RateLimitResult {
  allowed: boolean;
  remaining: number;
  resetAt: number;
  limitType?: "user" | "workspace";
}

/**
 * Narrow subset of the ioredis surface the limiter actually uses.
 *
 * `eval` matches ioredis: the script, how many of the following arguments are
 * keys, then those keys and the remaining arguments. Redis passes every
 * argument to Lua as a string, which is why the script converts them.
 */
export interface RateLimiterRedisPort {
  eval(script: string, numKeys: number, ...args: Array<string | number>): Promise<unknown>;
}

export interface RateLimiterConfig {
  redis: RateLimiterRedisPort;
  userPerHour: number;
  workspacePerHour: number;
  now?: () => number;
}

export interface RateLimiter {
  check(slackUserId: string, workspaceId: string): Promise<RateLimitResult>;
}

/** Window the limiter counts over. One hour, matching the per-hour limits. */
const WINDOW_MS = 60 * 60 * 1000;

/**
 * Prune, count, decide and spend — one indivisible operation.
 *
 * Returns `{allowed, remaining, limitType}` as integers, because Lua's `false`
 * reaches the client as a nil and a table is the only shape that carries three
 * values. `limitType` is 0 for none, 1 for the user limit, 2 for the workspace
 * limit; the caller maps it back.
 *
 * The two `EXPIRE` calls are what keep a key from outliving its window when a
 * user stops sending requests. They are refreshed on every admitted request
 * rather than set once, so a key is only ever collected after a full window of
 * silence.
 */
export const RATE_LIMIT_SCRIPT = `
local userKey, workspaceKey = KEYS[1], KEYS[2]
local now = tonumber(ARGV[1])
local windowStart = tonumber(ARGV[2])
local userLimit = tonumber(ARGV[3])
local workspaceLimit = tonumber(ARGV[4])
local member = ARGV[5]
local ttl = tonumber(ARGV[6])

redis.call('ZREMRANGEBYSCORE', userKey, '-inf', windowStart)
redis.call('ZREMRANGEBYSCORE', workspaceKey, '-inf', windowStart)

local userCount = redis.call('ZCARD', userKey)
local workspaceCount = redis.call('ZCARD', workspaceKey)

if userCount >= userLimit then
  return {0, 0, 1}
end
if workspaceCount >= workspaceLimit then
  return {0, workspaceLimit - workspaceCount, 2}
end

redis.call('ZADD', userKey, now, member)
redis.call('ZADD', workspaceKey, now, member)
redis.call('EXPIRE', userKey, ttl)
redis.call('EXPIRE', workspaceKey, ttl)

return {1, userLimit - userCount - 1, 0}
`;

export function createRateLimiter(deps: RateLimiterConfig): RateLimiter {
  const now = deps.now ?? (() => Date.now());
  const ttlSeconds = Math.ceil(WINDOW_MS / 1000) + 10;

  return {
    async check(slackUserId, workspaceId) {
      const t = now();
      const userKey = `ratelimit:user:${slackUserId}`;
      const workspaceKey = `ratelimit:workspace:${workspaceId}`;
      const member = `${t}-${Math.random()}`;

      let reply: unknown;
      try {
        reply = await deps.redis.eval(
          RATE_LIMIT_SCRIPT,
          2,
          userKey,
          workspaceKey,
          t,
          t - WINDOW_MS,
          deps.userPerHour,
          deps.workspacePerHour,
          member,
          ttlSeconds,
        );
      } catch (err) {
        // The limiter throttles; it does not authenticate. An unreachable Redis
        // must not take the service down with it.
        logger.error({ err, slackUserId }, "rate limiter script failed, failing open");
        return { allowed: true, remaining: -1, resetAt: t + WINDOW_MS };
      }

      if (!Array.isArray(reply) || reply.length < 3) {
        // A reply this cannot read is a reply this cannot enforce. Same posture
        // as an unreachable Redis rather than a guess at what was meant.
        logger.error(
          { slackUserId, reply },
          "rate limiter script returned an unreadable reply, failing open",
        );
        return { allowed: true, remaining: -1, resetAt: t + WINDOW_MS };
      }

      const [allowed, remaining, limitType] = reply as [number, number, number];
      if (allowed === 1) {
        return { allowed: true, remaining, resetAt: t + WINDOW_MS };
      }
      return {
        allowed: false,
        remaining,
        resetAt: t + WINDOW_MS,
        limitType: limitType === 2 ? "workspace" : "user",
      };
    },
  };
}
